baseURL = "https://diiegorgueez.me/"
languageCode = "en-us"
title = "diiegorgueez"
theme = "paper"

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
 # twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = 'DiegoRodriguezT'                 # github.com/YOUR_GITHUB_ID
 # instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'diegordguez'             # linkedin.com/in/YOUR_LINKEDIN_ID
 # mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
 # threads = '@YOUR_THREADS_ID'              # threads.net/@YOUR_THREADS_ID
 # rss = false                                # show rss icon
 search = true
  # home page profile
  avatar = 'https://diiegorgueez.me/avatar.jpg/'                 # gravatar email or image url
  name = 'Diego Rodríguez'
  bio = 'Student of Mathematics & Computer Engineering at URJC (Universidad Rey Juan Carlos) 🧑‍💻'

  google_tag_manager = "G-7BR7TC6N7L"
  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = false              # disable post navigation
  monoDarkIcon = false                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = false                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

[menu]

  [[menu.main]]
    identifier = "contact"
    name = "Contacto"
    url = "/contact/"
    weight = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
